### ISSUE TITLE
Javascript - No refresh token

### ISSUE THREAD

**Issue by matthuisman** [electrickiwi-nz/api-samples#2]
I noticed with the JS example - no refresh token is returned.
Is there anyway to get this?
Even if it's server side using my secret.

**Comment by electrickiwi-nz** [comment]
Matt - good spotting. When developing Javascript applications, they are inherently insecure because you can inspect the source to see what is communicated and saved to the browser. 

Therefore we use the OAuth2 [Implicit](https://auth0.com/docs/flows/implicit-flow-with-form-post) grant type which will only return a short-lived access token. There is more information found within this Okta article on when to use the Implicit grant type: 	
https://developer.okta.com/blog/2018/05/24/what-is-the-oauth2-implicit-grant-type#when-to-use-the-implicit-grant-type

If you are wanting a `refresh token` we suggest that you look to an [Authorisation Code](https://auth0.com/docs/flows/authorization-code-flow) grant type provided in the Node, Python or PHP samples. With this grant type, you will receive an access token and refresh token which you can use server-side to refresh the access token. 

You can learn more at our developer site under the [API Documentation](https://developer.electrickiwi.co.nz/api-documentation/) section.

**Comment by matthuisman** [comment]
thank you!
